// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Request
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Request";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DepartureStation("DepartureStation"),
		ArrivalStation("ArrivalStation"),
		DateTime("DateTime"),
		Departure("Departure"),
		hslAllowed("hslAllowed"),
		departureStation("MyFirstModule.departureStation"),
		arrivalStation("MyFirstModule.arrivalStation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Request"));
	}

	protected Request(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject)
	{
		if (requestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Request", requestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Request");

		this.requestMendixObject = requestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Request.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Request.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Request(context, mendixObject);
	}

	public static myfirstmodule.proxies.Request load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Request.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DepartureStation
	 */
	public final String getDepartureStation()
	{
		return getDepartureStation(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartureStation
	 */
	public final String getDepartureStation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DepartureStation.toString());
	}

	/**
	 * Set value of DepartureStation
	 * @param departurestation
	 */
	public final void setDepartureStation(String departurestation)
	{
		setDepartureStation(getContext(), departurestation);
	}

	/**
	 * Set value of DepartureStation
	 * @param context
	 * @param departurestation
	 */
	public final void setDepartureStation(com.mendix.systemwideinterfaces.core.IContext context, String departurestation)
	{
		getMendixObject().setValue(context, MemberNames.DepartureStation.toString(), departurestation);
	}

	/**
	 * @return value of ArrivalStation
	 */
	public final String getArrivalStation()
	{
		return getArrivalStation(getContext());
	}

	/**
	 * @param context
	 * @return value of ArrivalStation
	 */
	public final String getArrivalStation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ArrivalStation.toString());
	}

	/**
	 * Set value of ArrivalStation
	 * @param arrivalstation
	 */
	public final void setArrivalStation(String arrivalstation)
	{
		setArrivalStation(getContext(), arrivalstation);
	}

	/**
	 * Set value of ArrivalStation
	 * @param context
	 * @param arrivalstation
	 */
	public final void setArrivalStation(com.mendix.systemwideinterfaces.core.IContext context, String arrivalstation)
	{
		getMendixObject().setValue(context, MemberNames.ArrivalStation.toString(), arrivalstation);
	}

	/**
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.util.Date datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of Departure
	 */
	public final Boolean getDeparture()
	{
		return getDeparture(getContext());
	}

	/**
	 * @param context
	 * @return value of Departure
	 */
	public final Boolean getDeparture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.Departure.toString());
	}

	/**
	 * Set value of Departure
	 * @param departure
	 */
	public final void setDeparture(Boolean departure)
	{
		setDeparture(getContext(), departure);
	}

	/**
	 * Set value of Departure
	 * @param context
	 * @param departure
	 */
	public final void setDeparture(com.mendix.systemwideinterfaces.core.IContext context, Boolean departure)
	{
		getMendixObject().setValue(context, MemberNames.Departure.toString(), departure);
	}

	/**
	 * @return value of hslAllowed
	 */
	public final Boolean gethslAllowed()
	{
		return gethslAllowed(getContext());
	}

	/**
	 * @param context
	 * @return value of hslAllowed
	 */
	public final Boolean gethslAllowed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.hslAllowed.toString());
	}

	/**
	 * Set value of hslAllowed
	 * @param hslallowed
	 */
	public final void sethslAllowed(Boolean hslallowed)
	{
		sethslAllowed(getContext(), hslallowed);
	}

	/**
	 * Set value of hslAllowed
	 * @param context
	 * @param hslallowed
	 */
	public final void sethslAllowed(com.mendix.systemwideinterfaces.core.IContext context, Boolean hslallowed)
	{
		getMendixObject().setValue(context, MemberNames.hslAllowed.toString(), hslallowed);
	}

	/**
	 * @return value of departureStation
	 */
	public final myfirstmodule.proxies.Station getdepartureStation() throws com.mendix.core.CoreException
	{
		return getdepartureStation(getContext());
	}

	/**
	 * @param context
	 * @return value of departureStation
	 */
	public final myfirstmodule.proxies.Station getdepartureStation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Station result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.departureStation.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Station.load(context, identifier);
		return result;
	}

	/**
	 * Set value of departureStation
	 * @param departurestation
	 */
	public final void setdepartureStation(myfirstmodule.proxies.Station departurestation)
	{
		setdepartureStation(getContext(), departurestation);
	}

	/**
	 * Set value of departureStation
	 * @param context
	 * @param departurestation
	 */
	public final void setdepartureStation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Station departurestation)
	{
		if (departurestation == null)
			getMendixObject().setValue(context, MemberNames.departureStation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.departureStation.toString(), departurestation.getMendixObject().getId());
	}

	/**
	 * @return value of arrivalStation
	 */
	public final myfirstmodule.proxies.Station getarrivalStation() throws com.mendix.core.CoreException
	{
		return getarrivalStation(getContext());
	}

	/**
	 * @param context
	 * @return value of arrivalStation
	 */
	public final myfirstmodule.proxies.Station getarrivalStation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Station result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.arrivalStation.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Station.load(context, identifier);
		return result;
	}

	/**
	 * Set value of arrivalStation
	 * @param arrivalstation
	 */
	public final void setarrivalStation(myfirstmodule.proxies.Station arrivalstation)
	{
		setarrivalStation(getContext(), arrivalstation);
	}

	/**
	 * Set value of arrivalStation
	 * @param context
	 * @param arrivalstation
	 */
	public final void setarrivalStation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Station arrivalstation)
	{
		if (arrivalstation == null)
			getMendixObject().setValue(context, MemberNames.arrivalStation.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.arrivalStation.toString(), arrivalstation.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Request that = (myfirstmodule.proxies.Request) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Request";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
