// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Station
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Station";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		UICCode("UICCode"),
		LandCode("LandCode"),
		Station_Stations("MyFirstModule.Station_Stations");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Station(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Station"));
	}

	protected Station(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stationMendixObject)
	{
		if (stationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Station", stationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Station");

		this.stationMendixObject = stationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Station.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Station initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Station.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Station initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Station(context, mendixObject);
	}

	public static myfirstmodule.proxies.Station load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Station.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Station> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Station> result = new java.util.ArrayList<myfirstmodule.proxies.Station>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Station" + xpathConstraint))
			result.add(myfirstmodule.proxies.Station.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of UICCode
	 */
	public final String getUICCode()
	{
		return getUICCode(getContext());
	}

	/**
	 * @param context
	 * @return value of UICCode
	 */
	public final String getUICCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.UICCode.toString());
	}

	/**
	 * Set value of UICCode
	 * @param uiccode
	 */
	public final void setUICCode(String uiccode)
	{
		setUICCode(getContext(), uiccode);
	}

	/**
	 * Set value of UICCode
	 * @param context
	 * @param uiccode
	 */
	public final void setUICCode(com.mendix.systemwideinterfaces.core.IContext context, String uiccode)
	{
		getMendixObject().setValue(context, MemberNames.UICCode.toString(), uiccode);
	}

	/**
	 * @return value of LandCode
	 */
	public final String getLandCode()
	{
		return getLandCode(getContext());
	}

	/**
	 * @param context
	 * @return value of LandCode
	 */
	public final String getLandCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.LandCode.toString());
	}

	/**
	 * Set value of LandCode
	 * @param landcode
	 */
	public final void setLandCode(String landcode)
	{
		setLandCode(getContext(), landcode);
	}

	/**
	 * Set value of LandCode
	 * @param context
	 * @param landcode
	 */
	public final void setLandCode(com.mendix.systemwideinterfaces.core.IContext context, String landcode)
	{
		getMendixObject().setValue(context, MemberNames.LandCode.toString(), landcode);
	}

	/**
	 * @return value of Station_Stations
	 */
	public final myfirstmodule.proxies.Stations getStation_Stations() throws com.mendix.core.CoreException
	{
		return getStation_Stations(getContext());
	}

	/**
	 * @param context
	 * @return value of Station_Stations
	 */
	public final myfirstmodule.proxies.Stations getStation_Stations(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Stations result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Station_Stations.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Stations.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Station_Stations
	 * @param station_stations
	 */
	public final void setStation_Stations(myfirstmodule.proxies.Stations station_stations)
	{
		setStation_Stations(getContext(), station_stations);
	}

	/**
	 * Set value of Station_Stations
	 * @param context
	 * @param station_stations
	 */
	public final void setStation_Stations(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Stations station_stations)
	{
		if (station_stations == null)
			getMendixObject().setValue(context, MemberNames.Station_Stations.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Station_Stations.toString(), station_stations.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Station that = (myfirstmodule.proxies.Station) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Station";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
