// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nsconnector.proxies;

/**
 * Possible Itinerary
 */
public class ReisMogelijkheid
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reisMogelijkheidMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NSConnector.ReisMogelijkheid";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AantalOverstappen("AantalOverstappen"),
		GeplandeReisTijd("GeplandeReisTijd"),
		ActueleReisTijd("ActueleReisTijd"),
		GeplandeVertrekTijd("GeplandeVertrekTijd"),
		ActueleVertrekTijd("ActueleVertrekTijd"),
		GeplandeAankomstTijd("GeplandeAankomstTijd"),
		ActueleAankomstTijd("ActueleAankomstTijd"),
		Status("Status"),
		ReisMogelijkheid_TrainStatus("NSConnector.ReisMogelijkheid_TrainStatus");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ReisMogelijkheid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NSConnector.ReisMogelijkheid"));
	}

	protected ReisMogelijkheid(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reisMogelijkheidMendixObject)
	{
		if (reisMogelijkheidMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NSConnector.ReisMogelijkheid", reisMogelijkheidMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NSConnector.ReisMogelijkheid");

		this.reisMogelijkheidMendixObject = reisMogelijkheidMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ReisMogelijkheid.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static nsconnector.proxies.ReisMogelijkheid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nsconnector.proxies.ReisMogelijkheid.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static nsconnector.proxies.ReisMogelijkheid initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nsconnector.proxies.ReisMogelijkheid(context, mendixObject);
	}

	public static nsconnector.proxies.ReisMogelijkheid load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nsconnector.proxies.ReisMogelijkheid.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AantalOverstappen
	 */
	public final Integer getAantalOverstappen()
	{
		return getAantalOverstappen(getContext());
	}

	/**
	 * @param context
	 * @return value of AantalOverstappen
	 */
	public final Integer getAantalOverstappen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.AantalOverstappen.toString());
	}

	/**
	 * Set value of AantalOverstappen
	 * @param aantaloverstappen
	 */
	public final void setAantalOverstappen(Integer aantaloverstappen)
	{
		setAantalOverstappen(getContext(), aantaloverstappen);
	}

	/**
	 * Set value of AantalOverstappen
	 * @param context
	 * @param aantaloverstappen
	 */
	public final void setAantalOverstappen(com.mendix.systemwideinterfaces.core.IContext context, Integer aantaloverstappen)
	{
		getMendixObject().setValue(context, MemberNames.AantalOverstappen.toString(), aantaloverstappen);
	}

	/**
	 * @return value of GeplandeReisTijd
	 */
	public final String getGeplandeReisTijd()
	{
		return getGeplandeReisTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of GeplandeReisTijd
	 */
	public final String getGeplandeReisTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.GeplandeReisTijd.toString());
	}

	/**
	 * Set value of GeplandeReisTijd
	 * @param geplandereistijd
	 */
	public final void setGeplandeReisTijd(String geplandereistijd)
	{
		setGeplandeReisTijd(getContext(), geplandereistijd);
	}

	/**
	 * Set value of GeplandeReisTijd
	 * @param context
	 * @param geplandereistijd
	 */
	public final void setGeplandeReisTijd(com.mendix.systemwideinterfaces.core.IContext context, String geplandereistijd)
	{
		getMendixObject().setValue(context, MemberNames.GeplandeReisTijd.toString(), geplandereistijd);
	}

	/**
	 * @return value of ActueleReisTijd
	 */
	public final String getActueleReisTijd()
	{
		return getActueleReisTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of ActueleReisTijd
	 */
	public final String getActueleReisTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ActueleReisTijd.toString());
	}

	/**
	 * Set value of ActueleReisTijd
	 * @param actuelereistijd
	 */
	public final void setActueleReisTijd(String actuelereistijd)
	{
		setActueleReisTijd(getContext(), actuelereistijd);
	}

	/**
	 * Set value of ActueleReisTijd
	 * @param context
	 * @param actuelereistijd
	 */
	public final void setActueleReisTijd(com.mendix.systemwideinterfaces.core.IContext context, String actuelereistijd)
	{
		getMendixObject().setValue(context, MemberNames.ActueleReisTijd.toString(), actuelereistijd);
	}

	/**
	 * @return value of GeplandeVertrekTijd
	 */
	public final java.util.Date getGeplandeVertrekTijd()
	{
		return getGeplandeVertrekTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of GeplandeVertrekTijd
	 */
	public final java.util.Date getGeplandeVertrekTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.GeplandeVertrekTijd.toString());
	}

	/**
	 * Set value of GeplandeVertrekTijd
	 * @param geplandevertrektijd
	 */
	public final void setGeplandeVertrekTijd(java.util.Date geplandevertrektijd)
	{
		setGeplandeVertrekTijd(getContext(), geplandevertrektijd);
	}

	/**
	 * Set value of GeplandeVertrekTijd
	 * @param context
	 * @param geplandevertrektijd
	 */
	public final void setGeplandeVertrekTijd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date geplandevertrektijd)
	{
		getMendixObject().setValue(context, MemberNames.GeplandeVertrekTijd.toString(), geplandevertrektijd);
	}

	/**
	 * @return value of ActueleVertrekTijd
	 */
	public final java.util.Date getActueleVertrekTijd()
	{
		return getActueleVertrekTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of ActueleVertrekTijd
	 */
	public final java.util.Date getActueleVertrekTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActueleVertrekTijd.toString());
	}

	/**
	 * Set value of ActueleVertrekTijd
	 * @param actuelevertrektijd
	 */
	public final void setActueleVertrekTijd(java.util.Date actuelevertrektijd)
	{
		setActueleVertrekTijd(getContext(), actuelevertrektijd);
	}

	/**
	 * Set value of ActueleVertrekTijd
	 * @param context
	 * @param actuelevertrektijd
	 */
	public final void setActueleVertrekTijd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date actuelevertrektijd)
	{
		getMendixObject().setValue(context, MemberNames.ActueleVertrekTijd.toString(), actuelevertrektijd);
	}

	/**
	 * @return value of GeplandeAankomstTijd
	 */
	public final java.util.Date getGeplandeAankomstTijd()
	{
		return getGeplandeAankomstTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of GeplandeAankomstTijd
	 */
	public final java.util.Date getGeplandeAankomstTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.GeplandeAankomstTijd.toString());
	}

	/**
	 * Set value of GeplandeAankomstTijd
	 * @param geplandeaankomsttijd
	 */
	public final void setGeplandeAankomstTijd(java.util.Date geplandeaankomsttijd)
	{
		setGeplandeAankomstTijd(getContext(), geplandeaankomsttijd);
	}

	/**
	 * Set value of GeplandeAankomstTijd
	 * @param context
	 * @param geplandeaankomsttijd
	 */
	public final void setGeplandeAankomstTijd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date geplandeaankomsttijd)
	{
		getMendixObject().setValue(context, MemberNames.GeplandeAankomstTijd.toString(), geplandeaankomsttijd);
	}

	/**
	 * @return value of ActueleAankomstTijd
	 */
	public final java.util.Date getActueleAankomstTijd()
	{
		return getActueleAankomstTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of ActueleAankomstTijd
	 */
	public final java.util.Date getActueleAankomstTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActueleAankomstTijd.toString());
	}

	/**
	 * Set value of ActueleAankomstTijd
	 * @param actueleaankomsttijd
	 */
	public final void setActueleAankomstTijd(java.util.Date actueleaankomsttijd)
	{
		setActueleAankomstTijd(getContext(), actueleaankomsttijd);
	}

	/**
	 * Set value of ActueleAankomstTijd
	 * @param context
	 * @param actueleaankomsttijd
	 */
	public final void setActueleAankomstTijd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date actueleaankomsttijd)
	{
		getMendixObject().setValue(context, MemberNames.ActueleAankomstTijd.toString(), actueleaankomsttijd);
	}

	/**
	 * @return value of Status
	 */
	public final String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of ReisMogelijkheid_TrainStatus
	 */
	public final nsconnector.proxies.TravelPlan getReisMogelijkheid_TrainStatus() throws com.mendix.core.CoreException
	{
		return getReisMogelijkheid_TrainStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ReisMogelijkheid_TrainStatus
	 */
	public final nsconnector.proxies.TravelPlan getReisMogelijkheid_TrainStatus(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nsconnector.proxies.TravelPlan result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReisMogelijkheid_TrainStatus.toString());
		if (identifier != null)
			result = nsconnector.proxies.TravelPlan.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReisMogelijkheid_TrainStatus
	 * @param reismogelijkheid_trainstatus
	 */
	public final void setReisMogelijkheid_TrainStatus(nsconnector.proxies.TravelPlan reismogelijkheid_trainstatus)
	{
		setReisMogelijkheid_TrainStatus(getContext(), reismogelijkheid_trainstatus);
	}

	/**
	 * Set value of ReisMogelijkheid_TrainStatus
	 * @param context
	 * @param reismogelijkheid_trainstatus
	 */
	public final void setReisMogelijkheid_TrainStatus(com.mendix.systemwideinterfaces.core.IContext context, nsconnector.proxies.TravelPlan reismogelijkheid_trainstatus)
	{
		if (reismogelijkheid_trainstatus == null)
			getMendixObject().setValue(context, MemberNames.ReisMogelijkheid_TrainStatus.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReisMogelijkheid_TrainStatus.toString(), reismogelijkheid_trainstatus.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reisMogelijkheidMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nsconnector.proxies.ReisMogelijkheid that = (nsconnector.proxies.ReisMogelijkheid) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NSConnector.ReisMogelijkheid";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
