// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nsconnector.proxies;

/**
 * synonyms of the trainstation
 */
public class Synoniem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject synoniemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NSConnector.Synoniem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Naam("Naam"),
		Synoniem_Station("NSConnector.Synoniem_Station");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Synoniem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NSConnector.Synoniem"));
	}

	protected Synoniem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject synoniemMendixObject)
	{
		if (synoniemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NSConnector.Synoniem", synoniemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NSConnector.Synoniem");

		this.synoniemMendixObject = synoniemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Synoniem.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static nsconnector.proxies.Synoniem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nsconnector.proxies.Synoniem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static nsconnector.proxies.Synoniem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nsconnector.proxies.Synoniem(context, mendixObject);
	}

	public static nsconnector.proxies.Synoniem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nsconnector.proxies.Synoniem.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Naam
	 */
	public final String getNaam()
	{
		return getNaam(getContext());
	}

	/**
	 * @param context
	 * @return value of Naam
	 */
	public final String getNaam(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Naam.toString());
	}

	/**
	 * Set value of Naam
	 * @param naam
	 */
	public final void setNaam(String naam)
	{
		setNaam(getContext(), naam);
	}

	/**
	 * Set value of Naam
	 * @param context
	 * @param naam
	 */
	public final void setNaam(com.mendix.systemwideinterfaces.core.IContext context, String naam)
	{
		getMendixObject().setValue(context, MemberNames.Naam.toString(), naam);
	}

	/**
	 * @return value of Synoniem_Station
	 */
	public final nsconnector.proxies.Station getSynoniem_Station() throws com.mendix.core.CoreException
	{
		return getSynoniem_Station(getContext());
	}

	/**
	 * @param context
	 * @return value of Synoniem_Station
	 */
	public final nsconnector.proxies.Station getSynoniem_Station(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nsconnector.proxies.Station result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Synoniem_Station.toString());
		if (identifier != null)
			result = nsconnector.proxies.Station.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Synoniem_Station
	 * @param synoniem_station
	 */
	public final void setSynoniem_Station(nsconnector.proxies.Station synoniem_station)
	{
		setSynoniem_Station(getContext(), synoniem_station);
	}

	/**
	 * Set value of Synoniem_Station
	 * @param context
	 * @param synoniem_station
	 */
	public final void setSynoniem_Station(com.mendix.systemwideinterfaces.core.IContext context, nsconnector.proxies.Station synoniem_station)
	{
		if (synoniem_station == null)
			getMendixObject().setValue(context, MemberNames.Synoniem_Station.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Synoniem_Station.toString(), synoniem_station.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return synoniemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nsconnector.proxies.Synoniem that = (nsconnector.proxies.Synoniem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NSConnector.Synoniem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
