// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nsconnector.proxies;

/**
 * Departing train
 */
public class VertrekkendeTrein
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject vertrekkendeTreinMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NSConnector.VertrekkendeTrein";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ritnummer("Ritnummer"),
		VertrekTijd("VertrekTijd"),
		EindBestemming("EindBestemming"),
		TreinSoort("TreinSoort"),
		RouteTekst("RouteTekst"),
		Vervoerder("Vervoerder"),
		VertrekSpoor("VertrekSpoor"),
		VertrekkendeTrein_Departures("NSConnector.VertrekkendeTrein_Departures");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VertrekkendeTrein(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NSConnector.VertrekkendeTrein"));
	}

	protected VertrekkendeTrein(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vertrekkendeTreinMendixObject)
	{
		if (vertrekkendeTreinMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NSConnector.VertrekkendeTrein", vertrekkendeTreinMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NSConnector.VertrekkendeTrein");

		this.vertrekkendeTreinMendixObject = vertrekkendeTreinMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'VertrekkendeTrein.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static nsconnector.proxies.VertrekkendeTrein initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nsconnector.proxies.VertrekkendeTrein.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static nsconnector.proxies.VertrekkendeTrein initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nsconnector.proxies.VertrekkendeTrein(context, mendixObject);
	}

	public static nsconnector.proxies.VertrekkendeTrein load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nsconnector.proxies.VertrekkendeTrein.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ritnummer
	 */
	public final Integer getRitnummer()
	{
		return getRitnummer(getContext());
	}

	/**
	 * @param context
	 * @return value of Ritnummer
	 */
	public final Integer getRitnummer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Ritnummer.toString());
	}

	/**
	 * Set value of Ritnummer
	 * @param ritnummer
	 */
	public final void setRitnummer(Integer ritnummer)
	{
		setRitnummer(getContext(), ritnummer);
	}

	/**
	 * Set value of Ritnummer
	 * @param context
	 * @param ritnummer
	 */
	public final void setRitnummer(com.mendix.systemwideinterfaces.core.IContext context, Integer ritnummer)
	{
		getMendixObject().setValue(context, MemberNames.Ritnummer.toString(), ritnummer);
	}

	/**
	 * @return value of VertrekTijd
	 */
	public final java.util.Date getVertrekTijd()
	{
		return getVertrekTijd(getContext());
	}

	/**
	 * @param context
	 * @return value of VertrekTijd
	 */
	public final java.util.Date getVertrekTijd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.VertrekTijd.toString());
	}

	/**
	 * Set value of VertrekTijd
	 * @param vertrektijd
	 */
	public final void setVertrekTijd(java.util.Date vertrektijd)
	{
		setVertrekTijd(getContext(), vertrektijd);
	}

	/**
	 * Set value of VertrekTijd
	 * @param context
	 * @param vertrektijd
	 */
	public final void setVertrekTijd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date vertrektijd)
	{
		getMendixObject().setValue(context, MemberNames.VertrekTijd.toString(), vertrektijd);
	}

	/**
	 * @return value of EindBestemming
	 */
	public final String getEindBestemming()
	{
		return getEindBestemming(getContext());
	}

	/**
	 * @param context
	 * @return value of EindBestemming
	 */
	public final String getEindBestemming(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EindBestemming.toString());
	}

	/**
	 * Set value of EindBestemming
	 * @param eindbestemming
	 */
	public final void setEindBestemming(String eindbestemming)
	{
		setEindBestemming(getContext(), eindbestemming);
	}

	/**
	 * Set value of EindBestemming
	 * @param context
	 * @param eindbestemming
	 */
	public final void setEindBestemming(com.mendix.systemwideinterfaces.core.IContext context, String eindbestemming)
	{
		getMendixObject().setValue(context, MemberNames.EindBestemming.toString(), eindbestemming);
	}

	/**
	 * @return value of TreinSoort
	 */
	public final String getTreinSoort()
	{
		return getTreinSoort(getContext());
	}

	/**
	 * @param context
	 * @return value of TreinSoort
	 */
	public final String getTreinSoort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.TreinSoort.toString());
	}

	/**
	 * Set value of TreinSoort
	 * @param treinsoort
	 */
	public final void setTreinSoort(String treinsoort)
	{
		setTreinSoort(getContext(), treinsoort);
	}

	/**
	 * Set value of TreinSoort
	 * @param context
	 * @param treinsoort
	 */
	public final void setTreinSoort(com.mendix.systemwideinterfaces.core.IContext context, String treinsoort)
	{
		getMendixObject().setValue(context, MemberNames.TreinSoort.toString(), treinsoort);
	}

	/**
	 * @return value of RouteTekst
	 */
	public final String getRouteTekst()
	{
		return getRouteTekst(getContext());
	}

	/**
	 * @param context
	 * @return value of RouteTekst
	 */
	public final String getRouteTekst(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.RouteTekst.toString());
	}

	/**
	 * Set value of RouteTekst
	 * @param routetekst
	 */
	public final void setRouteTekst(String routetekst)
	{
		setRouteTekst(getContext(), routetekst);
	}

	/**
	 * Set value of RouteTekst
	 * @param context
	 * @param routetekst
	 */
	public final void setRouteTekst(com.mendix.systemwideinterfaces.core.IContext context, String routetekst)
	{
		getMendixObject().setValue(context, MemberNames.RouteTekst.toString(), routetekst);
	}

	/**
	 * @return value of Vervoerder
	 */
	public final String getVervoerder()
	{
		return getVervoerder(getContext());
	}

	/**
	 * @param context
	 * @return value of Vervoerder
	 */
	public final String getVervoerder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Vervoerder.toString());
	}

	/**
	 * Set value of Vervoerder
	 * @param vervoerder
	 */
	public final void setVervoerder(String vervoerder)
	{
		setVervoerder(getContext(), vervoerder);
	}

	/**
	 * Set value of Vervoerder
	 * @param context
	 * @param vervoerder
	 */
	public final void setVervoerder(com.mendix.systemwideinterfaces.core.IContext context, String vervoerder)
	{
		getMendixObject().setValue(context, MemberNames.Vervoerder.toString(), vervoerder);
	}

	/**
	 * @return value of VertrekSpoor
	 */
	public final String getVertrekSpoor()
	{
		return getVertrekSpoor(getContext());
	}

	/**
	 * @param context
	 * @return value of VertrekSpoor
	 */
	public final String getVertrekSpoor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.VertrekSpoor.toString());
	}

	/**
	 * Set value of VertrekSpoor
	 * @param vertrekspoor
	 */
	public final void setVertrekSpoor(String vertrekspoor)
	{
		setVertrekSpoor(getContext(), vertrekspoor);
	}

	/**
	 * Set value of VertrekSpoor
	 * @param context
	 * @param vertrekspoor
	 */
	public final void setVertrekSpoor(com.mendix.systemwideinterfaces.core.IContext context, String vertrekspoor)
	{
		getMendixObject().setValue(context, MemberNames.VertrekSpoor.toString(), vertrekspoor);
	}

	/**
	 * @return value of VertrekkendeTrein_Departures
	 */
	public final nsconnector.proxies.Departures getVertrekkendeTrein_Departures() throws com.mendix.core.CoreException
	{
		return getVertrekkendeTrein_Departures(getContext());
	}

	/**
	 * @param context
	 * @return value of VertrekkendeTrein_Departures
	 */
	public final nsconnector.proxies.Departures getVertrekkendeTrein_Departures(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		nsconnector.proxies.Departures result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VertrekkendeTrein_Departures.toString());
		if (identifier != null)
			result = nsconnector.proxies.Departures.load(context, identifier);
		return result;
	}

	/**
	 * Set value of VertrekkendeTrein_Departures
	 * @param vertrekkendetrein_departures
	 */
	public final void setVertrekkendeTrein_Departures(nsconnector.proxies.Departures vertrekkendetrein_departures)
	{
		setVertrekkendeTrein_Departures(getContext(), vertrekkendetrein_departures);
	}

	/**
	 * Set value of VertrekkendeTrein_Departures
	 * @param context
	 * @param vertrekkendetrein_departures
	 */
	public final void setVertrekkendeTrein_Departures(com.mendix.systemwideinterfaces.core.IContext context, nsconnector.proxies.Departures vertrekkendetrein_departures)
	{
		if (vertrekkendetrein_departures == null)
			getMendixObject().setValue(context, MemberNames.VertrekkendeTrein_Departures.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.VertrekkendeTrein_Departures.toString(), vertrekkendetrein_departures.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return vertrekkendeTreinMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nsconnector.proxies.VertrekkendeTrein that = (nsconnector.proxies.VertrekkendeTrein) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NSConnector.VertrekkendeTrein";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
