// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MyFirstModule module

	public static String getAPIEmail()
	{
		return (String)Core.getConfiguration().getConstantValue("MyFirstModule.APIEmail");
	}

	public static String getAPIKey()
	{
		return (String)Core.getConfiguration().getConstantValue("MyFirstModule.APIKey");
	}
}